baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'NBAstars'
theme='hugo-theme-stack'

[menu]
    [[menu.main]]
        identifier = "pagina_principal"
        name = "Pagina principal"
        title = "Pagina principal"
        url = "/pagina_principal/"
        weight = 1

    [[menu.main]]
        identifier = "equipos"
        name = "Equipos"
        title = "Equipos"
        url = "/equipos/"
        weight = 2

    [[menu.main]]
        identifier = "conferencias"
        name = "Conferencias"
        title = "Conferencias"
        url = "/conferencias/"
        weight = 3

    [[menu.main]]
        identifier = "estadisticas"
        name = "Estadisticas"
        title = "Estadisticas"
        url = "/estadisticas/"
        weight = 4

[params]
    css = ["css/estilos.css"]